# Generated by Django 5.1.4 on 2024-12-19 16:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileupload',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RenameField(
            model_name='fileupload',
            old_name='upload_date',
            new_name='uploaded_at',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='s3_etag',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='s3_metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='s3_url',
            field=models.URLField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileupload',
            name='s3_version_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['name'], name='api_fileupl_name_72a980_idx'),
        ),
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['uploaded_at'], name='api_fileupl_uploade_64f99a_idx'),
        ),
    ]
